### ISSUE TITLE
2. 커밋 목록들을 바탕으로 api 를 통해, 변경 내용 가져오기

### ISSUE THREAD

**Issue by GreenteaHT** [git-marvel/commit-guardians-client#10]
## 설명
응답 받아 저장한 커밋 목록을 바탕으로, tag를 통해 검사할 커밋들의 변경 내용(diff)를 요청
비동기적으로 필요한 요청을 보내고 알맞은 커밋에 변경 내용을 저장
API 요청 및 응답은 WebWorker를 통해 관리

## Todo
- [ ] 커밋 목록을 순회하며 tag를 통해 커밋 선택
  - [ ] 비동기적 요청 -> forEach
  - [ ] 해당 커밋의 변경 내용 URL을 이용해 변경 내용을 요청
  - [ ] 응답 받은 변경 내용을 해당 커밋 내용에 추가하여 저장
- [ ] #17

## 참고 자료
- [Notion](https://greentea-ice.notion.site/1-100-next-5-cbbcd299fff843d3b411f5c6bc974699?pvs=4)
