### ISSUE TITLE
5. 결과 목록 페이지 UI 를 보여주기

### ISSUE THREAD

**Issue by GreenteaHT** [git-marvel/commit-guardians-client#11]
## 설명
결과 목록 페이지 UI 구현

## Todo
- [ ] 표 생성
      * colum 정보
         1. COMMIT MESSAGE
         2. AUTHOR
         3. 결과 점수 (%)
         4. SHA
- [ ] 결과 점수를 바탕으로 가로 막대 그래프 구현
- [ ] 표 안에 데이터 넣기
- [ ] 표의 커밋 메시지 클릭 시 github의 해당 커밋 페이지로 이동
- [ ] 커밋 타입에 적합하지 않다고 판단된 커밋에 메시지 표시
- [ ] 결과 목록 필터링 기능 구현 ( % 값으로 필터링)

## 참고 자료

![image](https://github.com/user-attachments/assets/3d888263-b3e8-46b4-850c-378603f07318)
