### ISSUE TITLE
3-3. 100%인 커밋들 수 / 검사한 모든 커밋들 수 계산하기

### ISSUE THREAD

**Issue by shkimjune** [git-marvel/commit-guardians-client#14]
## 설명
커밋 검증 결과 페이지에 검증된 커밋들의 점수를 표시해준다.

```js
// commit Type = `remove` -> `diffPerCommit`

const checkRemoveCommitType = (diffPerCommit) => {
  // 1. 파일확장자 검사
  // 2. remove 대한 조건들을 다 검사
  ..
  return **(true 의 change 갯수 / 총 change 갯수) * 100** //  예시) 97%
}
```

//  97 점
// 88 점
// 30 점

## Todo
- [ ] 100%의 점수를 받은 커밋의 개수를 구하는 로직 구현
- [ ] 검증된 커밋과 skip된 커밋의 수를 구하는 로직 구현
- [ ] (100%인 커밋들의 수/ 검사한 모든 커밋들)의 결과를 기준으로 각 단계별 등급 지정: `getBadgeUrl`
        * 80% 이상 : 커밋규칙왕
        * 50% 이상 :  커밋노력파
        * 30% 이상 : 커밋 뉴비
        * 나머지 : 커밋 개성파
- [ ] 100%를 받은 커밋과 검증한 커밋의 개수를 표시할 UI 구현
- [ ] #19 

## 참고 자료
![Image](https://github.com/user-attachments/assets/6ad08394-1f18-4638-821d-23d2ccd17ea3)
