### ISSUE TITLE
4. 뱃지 UI 만들기 (이모지) + 클립보드 복사 기능

### ISSUE THREAD

**Issue by shkimjune** [git-marvel/commit-guardians-client#15]
## 설명
결과 페이지에서 보여줄 뱃지와 깃허브 repository README에 붙여넣기할 링크를 복사할 수 있는 기능
## Todo
- [x] #25
- [ ] 뱃지 UI 구현
- [ ] 커밋 % 결과에 따라 UI 결과값 분기처리
- [ ] 복사하기 버튼 UI 구현
- [ ] README에 붙여넣을 HTML태그 생성
- [ ] 클립보드 복사 기능 구현 (Clipboard API)
