### ISSUE TITLE
1-1. zustand 생성 및 설정

### ISSUE THREAD

**Issue by GreenteaHT** [git-marvel/commit-guardians-client#27]
## 설명
zustand를 fsd 폴더 구조에 맞게 설정

## Todo
- [ ] Store를 fsd 폴더 구조에 맞게 생성
- [ ] Store의 state와 action을 commit을 담을 수 있게 생성
- [ ] 평탄화 된 commit 목록 내용을 state에 저장
