### ISSUE TITLE
1-3. REST API를 GraphQL API로 리팩토링

### ISSUE THREAD

**Issue by GreenteaHT** [git-marvel/commit-guardians-client#34]
## 설명
고전적인 REST API를 쿼리 요청을 하는 GraphQL API로 대체하여 데이터를 선택적으로 요청하고 네트워크 부하를 줄일 수 있다.
사용자가 체감하는 대기시간을 줄일 수 있는 기대효과가 있음

## 스터디
graphQL 의 경우, fetch 나 axios 등을 사용해서 하나의 엔드포인트에 쿼리객체를 보내는 것이다. 자세한 것은 조사해보고 작성해보기!

## Todo
- [ ] 사용할 데이터를 선별
- [ ] 사용하고 있는 REST API를 모두 GraphQL API로 대체
- [ ] Zustand Store state 구조 변경
