### ISSUE TITLE
3-2-remove. remove 체크 로직 작성

### ISSUE THREAD

**Issue by GreenteaHT** [git-marvel/commit-guardians-client#4]
## 설명
`remove` 라는 커밋 타입의 역할은,
- 무조건 **파일이나 폴더를 삭제**하는 경우
- 모듈, 라이브러리를 삭제하는 경우
- 파일 삭제와 코드 수정을 같이 커밋한 경우는 해당하지 않는다

## Todo
- [ ] diff 파일확장자에 - 만 있는지 확인한다. + 가 없어야한다.
![Image](https://github.com/user-attachments/assets/a66d2cdd-cdb7-44f3-bfad-8417cfa1d28f)

- [ ]  모듈, 라이브러리를 삭제하는 경우
“@라이브러리:이름” 의 경우 → 이름으로 읽기엔 골뱅이 없는 라이브러리도 있기 때문에 제한이 있음
그리하여, 파일 확장자 (`.json`, `.yaml`) 등에서 삭제된 줄이 있는 경우, 모듈, 라이브러리라고 판단한다.

- [ ] 모든 changes 를 확인하여, 파일 삭제와 코드 수정을 같이 커밋한 경우는 remove % 에서 까인다.

- [ ] #23

## 참고 자료
[제 3조. remove: 파일 및 폴더를 삭제하는 커밋](https://www.notion.so/greentea-ice/POC-490f6939e567457486a5e614b76a8ae2?pvs=4#b861f5e226de4ebe88bf6e32b2302c94)
