### ISSUE TITLE
대용량 커밋 fetch 및 저장

### ISSUE THREAD

**Issue by howyoujini** [git-marvel/commit-guardians-client#54]
## 설명
session storage 의 한계: 대부분의 레포를 사용가능하게 해야함 [양이 많아도, 양이 없으면 ui 로 처리]

### indexedDB
- 브라우저에서 대용량 데이터를 구조화하여 저장할 수 있는 비관계형 데이터베이스.
- 용량이 크고, 저장할 수 있는 데이터의 양에 제한이 없거나 브라우저 정책에 따라 수 GB까지도 가능.
- **비동기 처리**가 가능해, 대량의 데이터도 부담 없이 다룰 수 있음.
- **객체 저장**이 가능해 JSON, BLOB 등 다양한 형식을 효율적으로 저장할 수 있음.
- 사용 예: 오프라인 기능을 지원하는 웹 애플리케이션, 게임 데이터 저장, 대용량 이미지 파일 저장 등.
    
단점
- **다루기 복잡함**: SQL과 비슷한 쿼리 방식이 아닌 트랜잭션 기반의 API를 사용해 다소 복잡하며, 비동기 API 때문에 코딩이 번거로울 수 있습니다.
- **속도 제한**: 대량의 데이터를 한꺼번에 처리할 때 로컬 저장소보다는 속도가 다소 느릴 수 있습니다.
- **브라우저 호환성 문제**: 모든 최신 브라우저에서 지원하지만, 오래된 브라우저에서는 사용이 제한될 수 있습니다.

## Todo
- [ ] 세션스토리지 계속 유지할 건지 결정
- [ ] 저장 방법 결정 - zustand? 메모리 관리 
- [ ] 검증할 수 있는 커밋들이 0 개라면, '텅' message 보여주기
