### ISSUE TITLE
커밋 formatStyle 도 디테일 화면에서 보여주기

### ISSUE THREAD

**Issue by howyoujini** [git-marvel/commit-guardians-client#77]
## 설명
커밋 formatStyle 도 디테일 화면에서 보여주기

## Todos
- [ ] formatStyle 을 커밋 엔티티에 저장하기
- [ ] 모든 formatStyle 을 순회하여 같은 formatStyle 들의 갯수를 저장하기
- [ ] formatStyle 을 Map() 으로 저장하고, 이를 퍼센트로 보여주기
