### ISSUE TITLE
커밋분석에 대한 가이드 문서 UI 구현

### ISSUE THREAD

**Issue by shkimjune** [git-marvel/commit-guardians-client#79]
## 설명
사용자에게 어떤 방식으로 커밋이 검증되고 있는지에 대한 안내입니다.

## TODO
- [x] 커밋 타입과 각 타입마다의 체크방법에 대한 설명 정리
- [x] `문의하기` 또는 `커밋 타입에 대한 의견` 을 받을 수 있는 구글 메일 생성
- [ ] 결과 페이지에 설명 문서에 대한 UI 구현
- [ ] 이메일 전송 폼 구현
- [x] #80

### 커밋 타입에 대한 설명
- 입력 가능한 레포지토리 커밋 메시지 형식
    
    *대소문자 구분이 없습니다. (Case-insensitive)
    
    1. 프리 픽스 스타일 (Prefix Style)
        
        `type(scope): subject` 
        
        예시: feat(auth): 로그인 API 연동
        
    2. 일반 텍스트 스타일 (Simple Text Style)
        
        `type subject` 
        
        예시: Add 로그인 API 연동
        
    3. 템플릿 기반 스타일 (Template Based Style)
        
        `[type] subject`
        
        예시: [ADD] 로그인 API 연동
        

- Commit Guardians가 확인하는 커밋 타입과 채점 방식
    - remove
        - 파일 및 폴더, 코드를 삭제한 커밋
            - 변경사항에 삭제한 부분만 포함됐는지 확인
        - 해당하지 않는 경우 예시
            - 파일 삭제와 코드 수정을 같이 커밋했을 경우
            - 변경사항에 코드의 추가된 부분이 포함된 경우
    - docs
        - 문서 작업만을 한 커밋
            - 문서에 사용되는 파일만 포함됐는지 확인
                - 이미지 파일 - `.img`, `.png`, `.jpeg`, `.svg`, `.ai`
                - 기타 문서 파일 - `.pdf` ,`.docs`, `.md`, `.mdx`, `.rst`
        - 해당하지 않는 경우 예시
            - 문서 파일과 소스 코드 파일의 수정사항을 같이 커밋했을 경우
    - style
        - 주로 코드 포매팅, 들여 쓰기, 코드 정렬 등 코드의 동작에 영향을 주지 않는 수정을 한 커밋
            - 파일명에 style을 나타내는 단어 확인 ("prettier", "eslint", "config”)
            - 변경사항에 특수문자(`,` , `'` , `"` , `\n` , `;` 등)만 수정됐는지 확인
            - 변경사항이 `console.log` 와 관련됐는지 확인
            - 요소들의 위치 변경 확인
                - tailwind className의 속성 순서
                - 객체 속성들의 순서
        - 해당하지 않는 경우 예시
            - 변수명 변경 등 style 체크 사항에 벗어난 경우
    - test
        - 테스트를 추가하거나 변경한 커밋
            - 테스트 코드를 작성한 파일만 포함됐는지 확인
                - `test`, `tests`, `spec`, `mock`
        - 해당하지 않는 경우 예시
            - test 검증 키워드가 파일명에 없거나 끝에 위치하지 않은 경우
                - `a/src/compiler-worker.ts`
                - `a/mock_feed_repository_impl.dart`
            - 테스트 코드 관련 파일이 아닌 설정 파일 등의 수정사항을 같이 커밋했을 경우
