### ISSUE TITLE
1. Github repository URL 을 이용하여 커밋 목록을 가져오기

### ISSUE THREAD

**Issue by GreenteaHT** [git-marvel/commit-guardians-client#9]
## 설명
Github repository의 URL을 이용하여 default branch의 commit 목록을 가져오는 기능을 구현
모든 커밋을 가져와야하기 때문에, page 단위로 모든 commit을 요청해야 하고, 요청을 최소화 하기 위해 페이지 당 commit 목록 요청을 최대(100개)로 설정
API 요청 및 응답은 WebWorker를 통해 관리

## Todo
- [ ] 첫 페이지의 commit 목록을 요청 및 응답 확인
- [ ] 첫 응답에서 총 요청 가능한 페이지 개수 추출
- [ ] 추가 페이지가 있다면 나머지 commit 목록 페이지 요청
  - [ ] 비동기적 요청 구현
  - [ ] 순차적인 응답 저장
- [ ] #16

## 참고 자료
- [Notion](https://greentea-ice.notion.site/1-100-next-5-cbbcd299fff843d3b411f5c6bc974699)
